package com.example.diplomski.entities;
// Generated Oct 24, 2013 2:39:14 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FizickoLice generated by hbm2java
 */
@Entity
@Table(name="fizicko_lice"
    ,catalog="diplomski"
)
public class FizickoLice extends PoslovniPartner implements java.io.Serializable, OpstiDomenskiObjekat {

     private Integer brLicneKarte;
     private String ime;
     private String prezime;
     private String telefon;

    public FizickoLice() {
    }

    public FizickoLice(Integer brLicneKarte, String ime, String prezime, String telefon) {
       this.brLicneKarte = brLicneKarte;
       this.ime = ime;
       this.prezime = prezime;
       this.telefon = telefon;
    }

    @Column(name="br_licne_karte")
    public Integer getBrLicneKarte() {
        return this.brLicneKarte;
    }
    
    public void setBrLicneKarte(Integer brLicneKarte) {
        this.brLicneKarte = brLicneKarte;
    }
    
    @Column(name="ime", length=32)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    
    @Column(name="prezime", length=32)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    
    @Column(name="telefon", length=32)
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }

	public String entityName() {
		return "FizickoLice";
	}

	@Override
	public String toString() {
		return  ime + " "+ prezime;
	}
	
	
	
}


