package com.example.diplomski.entities;

// default package
// Generated Oct 9, 2012 10:16:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FizickoLice generated by hbm2java
 */
@Entity
@Table(name = "fizicko_lice", catalog = "diplomski")
public class FizickoLice implements java.io.Serializable {

	private Integer idPoslovnogPartnera;
	private Integer brLicneKarte;
	private String ime;
	private String prezime;
	private String telefon;

	public FizickoLice() {
	}

	

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "poslovniPartner"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_poslovnog_partnera", unique = true, nullable = false)
	public Integer getIdPoslovnogPartnera() {
		return this.idPoslovnogPartnera;
	}

	public void setIdPoslovnogPartnera(Integer idPoslovnogPartnera) {
		this.idPoslovnogPartnera = idPoslovnogPartnera;
	}

	

	@Column(name = "br_licne_karte")
	public Integer getBrLicneKarte() {
		return this.brLicneKarte;
	}

	public void setBrLicneKarte(Integer brLicneKarte) {
		this.brLicneKarte = brLicneKarte;
	}

	@Column(name = "ime", length = 32)
	public String getIme() {
		return this.ime;
	}

	public void setIme(String ime) {
		this.ime = ime;
	}

	@Column(name = "prezime", length = 32)
	public String getPrezime() {
		return this.prezime;
	}

	public void setPrezime(String prezime) {
		this.prezime = prezime;
	}

	@Column(name = "telefon", length = 32)
	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

}
