package com.example.diplomski.entities;
// Generated Oct 24, 2013 2:39:14 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KontaktOsobe generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="kontakt_osobe" ,catalog="diplomski")
public class KontaktOsobe  implements java.io.Serializable,OpstiDomenskiObjekat {


     private Integer idKontaktOsobe;
     private PoslovniPartner poslovniPartner;
     private String ime;
     private String prezime;
     private String telefon;
     private String email;

    public KontaktOsobe() {
    }

	
    public KontaktOsobe(PoslovniPartner poslovniPartner) {
        this.poslovniPartner = poslovniPartner;
    }
    public KontaktOsobe(PoslovniPartner poslovniPartner, String ime, String prezime, String telefon, String email) {
       this.poslovniPartner = poslovniPartner;
       this.ime = ime;
       this.prezime = prezime;
       this.telefon = telefon;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_kontakt_osobe", unique=true, nullable=false)
    public Integer getIdKontaktOsobe() {
        return this.idKontaktOsobe;
    }
    
    public void setIdKontaktOsobe(Integer idKontaktOsobe) {
        this.idKontaktOsobe = idKontaktOsobe;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_poslovnog_partnera", nullable=false)
    public PoslovniPartner getPoslovniPartner() {
        return this.poslovniPartner;
    }
    
    public void setPoslovniPartner(PoslovniPartner poslovniPartner) {
        this.poslovniPartner = poslovniPartner;
    }
    
    @Column(name="ime", length=32)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    
    @Column(name="prezime", length=32)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    
    @Column(name="telefon", length=32)
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    
    @Column(name="email", length=32)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


	public String entityName() {
		return "KontaktOsobe";
	}


	public String idColumName() {
		// TODO Auto-generated method stub
		return null;
	}


	public Integer idColumnValue() {
		// TODO Auto-generated method stub
		return null;
	}





}


