package com.example.diplomski.entities;
// Generated Oct 24, 2013 2:39:14 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PravnoLice generated by hbm2java
 */
@Entity
@Table(name="pravno_lice"
    ,catalog="diplomski"
)
public class PravnoLice extends PoslovniPartner implements java.io.Serializable {


     private String pib;
     private String naziv;

    public PravnoLice() {
    }

    public PravnoLice(PoslovniPartner poslovniPartner, String pib, String naziv) {
       this.pib = pib;
       this.naziv = naziv;
    }
   
    @Column(name="pib", length=64)
    public String getPib() {
        return this.pib;
    }
    
    public void setPib(String pib) {
        this.pib = pib;
    }
    
    @Column(name="naziv", length=64)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

	@Override
	public String entityName() {
		return "PravnoLice";
	}

    
}


