package com.example.diplomski.entities;

// default package
// Generated Oct 9, 2012 10:16:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PravnoLice generated by hbm2java
 */
@Entity
@Table(name = "pravno_lice", catalog = "diplomski")
public class PravnoLice implements java.io.Serializable {

	private Integer idPoslovnogPartnera;

	private String pib;
	private String naziv;

	public PravnoLice() {
	}


	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "poslovniPartner"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_poslovnog_partnera", unique = true, nullable = false)
	public Integer getIdPoslovnogPartnera() {
		return this.idPoslovnogPartnera;
	}

	public void setIdPoslovnogPartnera(Integer idPoslovnogPartnera) {
		this.idPoslovnogPartnera = idPoslovnogPartnera;
	}

	

	@Column(name = "pib", length = 64)
	public String getPib() {
		return this.pib;
	}

	public void setPib(String pib) {
		this.pib = pib;
	}

	@Column(name = "naziv", length = 64)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

}
