package com.example.diplomski.entities;
// Generated Oct 24, 2013 2:39:14 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProizvodUsluga generated by hbm2java
 */
@Entity
@Table(name="proizvod_usluga"
    ,catalog="diplomski"
)

@Inheritance(strategy=InheritanceType.JOINED)
public class ProizvodUsluga  implements java.io.Serializable, OpstiDomenskiObjekat {


     private Integer idProizvodUsluga;
     private String naziv;
     private Double cena;
     private Set<StavkaRacuna> stavkaRacunas = new HashSet<StavkaRacuna>(0);

    public ProizvodUsluga() {
    }

    public ProizvodUsluga(String naziv, Double cena, Set<StavkaRacuna> stavkaRacunas) {
       this.naziv = naziv;
       this.cena = cena;
       this.stavkaRacunas = stavkaRacunas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_proizvod_usluga", unique=true, nullable=false)
    public Integer getIdProizvodUsluga() {
        return this.idProizvodUsluga;
    }
    
    public void setIdProizvodUsluga(Integer idProizvodUsluga) {
        this.idProizvodUsluga = idProizvodUsluga;
    }
    
    @Column(name="naziv", length=45)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    
    @Column(name="cena", precision=22, scale=0)
    public Double getCena() {
        return this.cena;
    }
    
    public void setCena(Double cena) {
        this.cena = cena;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="proizvodUsluga")
    public Set<StavkaRacuna> getStavkaRacunas() {
        return this.stavkaRacunas;
    }
    
    public void setStavkaRacunas(Set<StavkaRacuna> stavkaRacunas) {
        this.stavkaRacunas = stavkaRacunas;
    }

	public String entityName() {
		
		return "ProizvodUsluga";
	}

	public String idColumName() {
		// TODO Auto-generated method stub
		return null;
	}




}


