package com.example.diplomski.entities;
// Generated Oct 24, 2013 2:39:14 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Proizvod generated by hbm2java
 */
@Entity
@Table(name="proizvod"
    ,catalog="diplomski"
)
public class Proizvod extends ProizvodUsluga  implements java.io.Serializable {


     private TipProizvoda tipProizvoda;
     private Integer kolicina;

    public Proizvod() {
    }

	
    public Proizvod(TipProizvoda tipProizvoda) {
        this.tipProizvoda = tipProizvoda;
    }
    public Proizvod(TipProizvoda tipProizvoda, Integer kolicina) {
       this.tipProizvoda = tipProizvoda;
       this.kolicina = kolicina;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tip_proizvoda", nullable=false)
    public TipProizvoda getTipProizvoda() {
        return this.tipProizvoda;
    }
    
    public void setTipProizvoda(TipProizvoda tipProizvoda) {
        this.tipProizvoda = tipProizvoda;
    }
    
    @Column(name="kolicina")
    public Integer getKolicina() {
        return this.kolicina;
    }
    
    public void setKolicina(Integer kolicina) {
        this.kolicina = kolicina;
    }
}


