package com.example.diplomski.entities;
// Generated Oct 24, 2013 2:39:14 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StavkaRacuna generated by hbm2java
 */
@Entity
@Table(name="stavka_racuna"
    ,catalog="diplomski"
)
public class StavkaRacuna  implements java.io.Serializable {


     private Integer idStavkeRacuna;
     private ProizvodUsluga proizvodUsluga;
     private Racun racun;
     private Integer kolicina;

    public StavkaRacuna() {
    	kolicina = new Integer(1);
    }

	
    public StavkaRacuna(ProizvodUsluga proizvodUsluga, Racun racun) {
        this.proizvodUsluga = proizvodUsluga;
        this.racun = racun;
    }
    public StavkaRacuna(ProizvodUsluga proizvodUsluga, Racun racun, Integer kolicina) {
       this.proizvodUsluga = proizvodUsluga;
       this.racun = racun;
       this.kolicina = kolicina;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_stavke_racuna", unique=true, nullable=false)
    public Integer getIdStavkeRacuna() {
        return this.idStavkeRacuna;
    }
    
    public void setIdStavkeRacuna(Integer idStavkeRacuna) {
        this.idStavkeRacuna = idStavkeRacuna;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="proizvod_usluga", nullable=false)
    public ProizvodUsluga getProizvodUsluga() {
        return this.proizvodUsluga;
    }
    
    public void setProizvodUsluga(ProizvodUsluga proizvodUsluga) {
        this.proizvodUsluga = proizvodUsluga;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_racuna", nullable=false)
    public Racun getRacun() {
        return this.racun;
    }
    
    public void setRacun(Racun racun) {
        this.racun = racun;
    }
    
    @Column(name="kolicina")
    public Integer getKolicina() {
        return this.kolicina;
    }
    
    public void setKolicina(Integer kolicina) {
        this.kolicina = kolicina;
    }
    
    @Transient
    public Double getCena(){
    	return proizvodUsluga.getCena() * kolicina;
    }
}


