package com.example.diplomski.entities;
// Generated Oct 24, 2013 2:39:14 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usluga generated by hbm2java
 */
@Entity
@Table(name="usluga"
    ,catalog="diplomski"
)
public class Usluga extends ProizvodUsluga implements java.io.Serializable {


     private String opis;

    public Usluga() {
    }

    public Usluga(String opis) {
       this.opis = opis;
    }

    @Column(name="opis", length=45)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

	@Override
	public String entityName() {
		return "Usluga";
	}

	@Override
	public Integer idColumnValue() {
		return getIdProizvodUsluga();
	}

	@Override
	public String idColumName() {
		// TODO Auto-generated method stub
		return super.idColumName();
	}
	
	




}


