package com.example.diplomski.entities;

// default package
// Generated Oct 9, 2012 10:16:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Usluga generated by hbm2java
 */
@Entity
@Table(name = "usluga", catalog = "diplomski")
public class Usluga implements java.io.Serializable {

	private int idProizvodUsluga;
	private String opis;

	public Usluga() {
	}


	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "proizvodUsluga"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_proizvod_usluga", unique = true, nullable = false)
	public int getIdProizvodUsluga() {
		return this.idProizvodUsluga;
	}

	public void setIdProizvodUsluga(int idProizvodUsluga) {
		this.idProizvodUsluga = idProizvodUsluga;
	}

	

	@Column(name = "opis", length = 45)
	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

}
